@url = http://localhost:5010/api
@accessToken = test

@userGid = test
@access-token = test

###
POST {{url}}/sign-up
Content-Type: application/json

{
    "userName" : "sashaTkachuk",
    "email" : "sashatkachuk09@ukr.net",
    "password" : "Password1",
    "roleGid" : null
}

###
POST {{url}}/sign-in
Content-Type: application/json

{
    "userName" : "sashaTkachuk",
    "password" : "Password1"
}

###
PATCH  {{url}}/revoke-token
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "userGid" : "{{userGid}}"
}