version: '3.4'

services:
  postgres:
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  jobwrapper.gateway:
    container_name: jobwrapper-gateway
    ports:
      - "5000:80"

  users.presentation:
    container_name: users-service
    ports:
      - "5010:80"

  vacancies.presentation:
    container_name: vacancies-service
    ports:
      - "5020:80"

  frontend:
    container_name: frontend
    ports:
      - "3000:3000"

