version: "3.7"

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - job-wrapper
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    tty: true
    restart: unless-stopped
    networks:
      - job-wrapper
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

 # redis:
 #   image: redis
 #  container_name: redis
 #   networks:
 #     - job-wrapper
 #   ports:
 #     - "6379:6379"
 #   volumes: 
 #     - redis:/var/lib/redis

networks:
  job-wrapper:
    name: job-wrapper

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
